### ISSUE TITLE
Decoding signatures on L1 transactions through the Gelato relay

### ISSUE THREAD

**Issue by michaelfioretti** [gelatodigital/relay-sdk#34]
I'm trying to determine what addresses signed a Gnosis safe transaction that has been sent through the Gelato Relay. I know that the Gnosis `execTransaction` data is encoded and sent to the relay, and I am successfully able to decode the `transaction.data` using the `Gelato` ABI. 

I figured since this was able to be decoded, that I had to decode the data sent as a `Message` struct to the relay itself. After I decode this data, I see that the next chunk of decoding is looking for a `sighash` equal to `0x27be3c24`. My first thought was that I needed to use the `EIP721Proxy` contract, but that isn't working. 

Any pointers towards which ABI I need to use to decode this data would be greatly apreciated.

**Comment by denis-pingin** [comment]
@michaelfioretti could you provide an example transaction hash?

**Comment by michaelfioretti** [comment]
@denis-pingin sure thing!

[Link to transaction](https://mumbai.polygonscan.com/tx/0x340c4894962784396bd3e5e9fcee0a878bdc7f1db8b4474dc352dbaf72fce258)

**Comment by michaelfioretti** [comment]
@denis-pingin I'll also note that I was able to decode the first part of that transaction's data, and got this:

```
[
  [
    "0x9c2eb4e483a371b98da89ea33821db11be84b18eb150c8480dee45f79390a6f9",
    [
      "0x75bA5Af8EFFDCFca32E1e288806d54277D1fde99",
      "0x27be3c2400000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000bb331a4ccb529a192afed55ad75ec099d8a6f52c000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000184300000000000000000000000000000000000000000000000000000000009896809c2eb4e483a371b98da89ea33821db11be84b18eb150c8480dee45f79390a6f90000000000000000000000000000000000000000000000000000000000013881000000000000000000000000770205f7424dcc88cdce47a5a9678684a0690ea9000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000002246a761202000000000000000000000000e5cfdd15b8db27408d4d46aa4a1cded2f255662d00000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030d4000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082a4523db5088a0a32b0ed3e36fbc26300a83b4017855601f88be9140182d03dd727f49e22b28a9d848a6dc94b7aa72c4d214bdec915945fd11626a151d48abfd91b76e3516912798adaebedf6b115e8a7dede798789606cd2442e483576916285bd1e6f10e03845b53175e580141e738de8c516b7f5cdb3b0a37ec8ad0a662c9b1e1c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      { "type": "BigNumber", "hex": "0x64f9efae" },
      { "type": "BigNumber", "hex": "0x64f9f332" }
    ],
    "0xb58e1c13b4612658007b28d03aea19457e3aadefe29e488be141ecd53d8b6bfe347ca54ef8187a9ca054c5b41642fe3bbade0180e3aa30359f543dc7fdd2c9011b",
    "0x341a2d6a5afa3d4758f6928f2c8bfe53bae51a60d000dc563708482fde73cb2438001e17418c9807a4601b875e9baa78b77c3034adcd009bc56351d6bb600ca91b"
  ]
]
```

Where I'm stuck is trying to decode the second argument to the decoded array, which looks like it's a `Message`, but I could be wrong. According to the struct, the `data` seems to be this string:

 `0x27be3c2400000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000bb331a4ccb529a192afed55ad75ec099d8a6f52c000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000184300000000000000000000000000000000000000000000000000000000009896809c2eb4e483a371b98da89ea33821db11be84b18eb150c8480dee45f79390a6f90000000000000000000000000000000000000000000000000000000000013881000000000000000000000000770205f7424dcc88cdce47a5a9678684a0690ea9000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000002246a761202000000000000000000000000e5cfdd15b8db27408d4d46aa4a1cded2f255662d00000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030d4000000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082a4523db5088a0a32b0ed3e36fbc26300a83b4017855601f88be9140182d03dd727f49e22b28a9d848a6dc94b7aa72c4d214bdec915945fd11626a151d48abfd91b76e3516912798adaebedf6b115e8a7dede798789606cd2442e483576916285bd1e6f10e03845b53175e580141e738de8c516b7f5cdb3b0a37ec8ad0a662c9b1e1c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

**Comment by denis-pingin** [comment]
@michaelfioretti the next one is this call being made from Gelato Diamond to GelatoRelay1Balance contract, passing the `message.data` as calldata: https://github.com/gelatodigital/relay-contracts/blob/master/contracts/GelatoRelay1Balance.sol#L36C14-L36C27

**Comment by michaelfioretti** [comment]
@denis-pingin ah gotcha - I _knew_ it was something related to `Gelato`. Thank you so much - I appreciate the help! I was able to continue after decoding from `GelatoRelay1Balance.sol` to getting my signatures. Closing for now
