### ISSUE TITLE
Viem support

### ISSUE THREAD

**Issue by Julien-R44** [gelatodigital/relay-sdk#37]
Do you have any plan to add support for [viem](https://viem.sh/) or replace Ethers with it in a future version?

Viem is becoming increasingly popular and, in my opinion, will quickly become more used than Ethers. The latest version of Wagmi, for example, has completely replaced ethers with Viem. 

I use Viem on my project, and although I can have some sort of interoperability with @gelato/relay-sdk via a [Viem -> Ethers adapter](https://wagmi.sh/react/ethers-adapters), it would still be better to be able to use Viem only.

Thanks!

**Comment by denis-pingin** [comment]
@Julien-R44 it's on our roadmap, but there is no ETA yet

**Comment by Julien-R44** [comment]
Closing since it seems you guys worked on it https://docs.gelato.network/web3-services/relay/relay-sdk-with-viem

Thanks !!
