### ISSUE TITLE
Expose TaskState or use string literal

### ISSUE THREAD

**Issue by GrandSchtroumpf** [gelatodigital/relay-sdk#40]
Currently `TaskState` is not part of the entry point definition type so we cannot use it to compare the status against the current task.
Another (better) option would be to use string literal instead of enum.
1. string literal are not compiled to Javascript, so it reduce size (see diff [here](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKghgZwNYGUAuc3CgbwLABQUxUAwgBbADGSACqACYCWIA5lALxQBEF1djFq24AaQiSgBRAB7V6IZm048ZcwW1HiSAdThM0QgGIB7AE6ljIAGZNTETE0vLuu-UbMXrt+wcuaiJKpUKGBUVMAICM5BIWERCP4SQQBKwABuwKZYDNGyVKkZWcAMiSSkcCDhADZVxc7llcA1xdyEAL6EVJYIaFA9mMAAjMrwyOgDAHQN1bUMANyEhAD0S1AAtBtQAGooiwRoAJ4ADtgA4k2YxqOoGFj1lDTyisJQAD4qeU9C3G88rgZsEzmSw2OwOPy-bgxULhSI-d5QvIFTLZeE8aZNWbcBYELogHp9W7AABMAC4oOcqpdruM7lwAOR8R7qVj0uZAA))
2. we won't need to import the enum to compare, but still get autocomplete
3. we won't need to prefix with `TaskState` to compare the value. In these days when prettier makes every characters on the line count it's always a relief 😉.

`enum`
```typescript
if (task.taskState === TaskState.Cancelled) ...
```
`string-literal`
```typescript
if (task.taskState === 'Cancelled') ...
```

**Comment by denis-pingin** [comment]
@GrandSchtroumpf fixed in [v5.5.5](https://github.com/gelatodigital/relay-sdk/releases/tag/v5.5.5)
